config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :custom_restful do
    collection do
      post "new", as: :new
    end
    member do
      post "edit", as: :edit
    end
  end

  resources :login, only: [:new] do
    collection do
      post "new"
      get :logout
    end
  end

  resources :top, only: [:index]

  resource :system_config,
    only: [:edit, :update] do
    member do
      post "edit", as: :edit
    end
  end

  resources :reasons,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :leave_types,
    only: [:index, :new, :edit],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :articles,
    only: [:index, :show, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :special_days,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :attendances,
    only: [:index, :destroy] do
    collection do
      match :save, via: :all
      post :specific_month
    end
  end

  root to: redirect("login/new")

  post "/toggle_sidebar" => "application#toggle_sidebar"

  # page not found
  get "*path", controller: "application", action: "render_404"
end

app/models/article.rb
# frozen_string_literal: true
class Article < ApplicationRecord
  belongs_to :user

  # 有効データ
  scope :availability, -> {
    where(deleted: CONSTANTS::DISABLE_FLAG)
  }

  # 掲載期間中データ
  scope :posted_period, -> {
    today = Date.today.strftime(I18n.t(:default_date_format, separate: nil))
    table = arel_table
    query = table[:posted_start_date_ymd].lteq(today)
    query = query.and(table[:posted_end_date_ymd].gteq(today))
    availability.where(query)
  }

  # 新着順
  scope :order_new, -> {
    order(updated_at: :desc)
  }

  validates :title,
            presence: true
  validates :body,
            presence: true
  validates :posted_start_date_text,
            presence: true,
            date: { format: I18n.t(:date_format), allow_blank: true }
  validates :posted_end_date_text,
            presence: true,
            date: { format: I18n.t(:date_format), allow_blank: true }
  validate :validate_posted_period

  def posted_start_date
    Date.strptime(posted_start_date_ymd, I18n.t(:default_date_format, separate: nil))
  rescue
    nil
  end

  def posted_start_date_text
    return @posted_start_date_text unless @posted_start_date_text.blank?
    posted_start_date.strftime(I18n.t(:date_format))
  rescue
    nil
  end

  def posted_start_date_text=(value)
    date_value = Date.strptime(value, I18n.t(:date_format))
    self.posted_start_date_ymd = date_value.strftime(I18n.t(:default_date_format, separate: nil))
  rescue
    self.posted_start_date_ymd = nil
  ensure
    @posted_start_date_text = value
  end

  def posted_end_date
    Date.strptime(posted_end_date_ymd, I18n.t(:default_date_format, separate: nil))
  rescue
    nil
  end

  def posted_end_date_text
    return @posted_end_date_text unless @posted_end_date_text.blank?
    posted_end_date.strftime(I18n.t(:date_format))
  rescue
    nil
  end

  def posted_end_date_text=(value)
    date = Date.strptime(value, I18n.t(:date_format))
    self.posted_end_date_ymd = date.strftime(I18n.t(:default_date_format, separate: nil))
  rescue
    self.posted_end_date_ymd = nil
  ensure
    @posted_end_date_text = value
  end

  def created_at_text
    return if created_at.blank?
    created_at.strftime(I18n.t(:date_format))
  end

  def soft_delete
    update(deleted: CONSTANTS::ENABLE_FLAG)
  end

  private

  def validate_posted_period
    return if errors.messages[:posted_start_date_text].present? || errors.messages[:posted_end_date_text].present?
    return if posted_start_date_text.blank? || posted_end_date_text.blank?
    return if posted_start_date_text <= posted_end_date_text
    errors.add(:posted_start_date, :after_end_date)
    errors.add(:posted_end_date, :before_start_date)
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
class ArticlesController < ApplicationController
  before_action :required_admin_authority
  before_action :check_create_article_params, only: [:new]
  before_action :check_update_article_params, only: [:edit]

  def index
    @articles = Article.availability.order_new
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    if request.get?
      today    = Date.today
      end_date = CONSTANTS::DEFAULT_POSTED_PERIOD.month.from_now
      @article = Article.new
      @article.posted_start_date_text = today.strftime(I18n.t(:date_format))
      @article.posted_end_date_text   = end_date.strftime(I18n.t(:date_format))
    else
      @article.save
      flash[:notice] = t(".create_article")
      redirect_to articles_path
    end
  end

  def edit
    if request.get?
      @article = Article.find(params[:id])
    else
      @article.save
      flash[:notice] = t(".update_article")
      redirect_to articles_path
    end
  end

  def destroy
    Article.find(params[:id]).soft_delete
    flash[:notice] = t(".delete_article")
    redirect_to articles_path
  end

  private

  def check_create_article_params
    return if params[:article].blank?
    @article = Article.new(article_params)
    return if @article.valid?
    render action: :new
  end

  def check_update_article_params
    return if params[:article].blank?
    @article = Article.find(params[:id])
    @article.attributes = article_params
    return if @article.valid?
    render action: :edit
  end

  def article_params
    params.require(:article).permit(
      :user_id,
      :posted_start_date_text,
      :posted_end_date_text,
      :title,
      :body
    )
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= f.hidden_field :user_id, value: current_user.id %>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:posted_start_date_ymd) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :posted_start_date_text, required: true, class: "datepicker form-control flat" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:posted_end_date_ymd) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :posted_end_date_text, required: true, class: "datepicker form-control flat" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:title) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :title, required: true, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:body) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_area :body, required: true, class: "textarea form-control", rows: 10, maxlength: 1000 %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $(".datepicker").datepicker({
      language: "ja",
      format:   "<%= t("datepicker.format") %>"
    }).on("changeDate", function(e){
      $(this).datepicker("hide");
    });
  });
</script>

app/views/articles/edit.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @article, url: { action: :edit }, html: { class: "form-horizontal" }, method: :post do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_article"),
                  data:  { disable_with: t(:processing) },
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), article_path(@article),
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/articles/index.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"><%= t(".list") %></h3>
            </div>
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                  <table id="article_table" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>
                          <%= Article.human_attribute_name(:created_at) %>
                        </th>
                        <th>
                          <%= Article.human_attribute_name(:title) %>
                        </th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @articles.each do |article| %>
                        <tr>
                          <td>
                            <%= article.created_at_text %>
                          </td>
                          <td>
                            <%= article.title %>
                          </td>
                          <td>
                            <%= link_to t(".show"), article_path(article),
                              class: "btn btn-success" %>
                          </td>
                          <td>
                            <%= link_to t(".delete"), article_path(article),
                              method: :delete,
                              class:   "btn btn-danger" %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%== datatable_script("article_table",
                                        0,
                                        { order: "desc",
                                          column_defs: [-1, -2] }) %>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <%= link_to t(".new_article"), new_article_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
              <%= link_to t(".back"), top_index_path,
                method: :get,
                class:  "btn btn-primary btn-lg pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/articles/new.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @article, url: { action: :new }, html: { class: "form-horizontal" } do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_article"),
                  data:  { disable_with: t(:processing) },
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), articles_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/articles/show.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @article, html: { class: "form-horizontal" } do |f| %>
              <div class="box-body">
                <div class="form-group">
                  <label class="col-sm-2 control-label">
                    <%= @article.class.human_attribute_name(:posted_start_date_ymd) %>
                  </label>
                  <div class="col-sm-10">
                    <%= f.text_field :posted_start_date_text,
                      class:    "form-control",
                      readonly: true %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-2 control-label">
                    <%= @article.class.human_attribute_name(:posted_end_date_ymd) %>
                  </label>
                  <div class="col-sm-10">
                    <%= f.text_field :posted_end_date_text,
                      class:    "form-control",
                      readonly: true %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-2 control-label">
                    <%= @article.class.human_attribute_name(:title) %>
                  </label>
                  <div class="col-sm-10">
                    <%= f.text_field :title,
                      class:    "form-control",
                      readonly: true %>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-2 control-label">
                    <%= @article.class.human_attribute_name(:body) %>
                  </label>
                  <div class="col-sm-10">
                    <%= f.text_area :body,
                      class:     "textarea form-control",
                      rows:      10,
                      maxlength: 1000,
                      readonly:  true %>
                  </div>
                </div>
              </div>
              <div class="box-footer">
                <%= link_to t(".edit_article"), edit_article_path(@article.id),
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), articles_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>