config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :custom_restful do
    collection do
      post "new", as: :new
    end
    member do
      post "edit", as: :edit
    end
  end

  resources :login, only: [:new] do
    collection do
      post "new"
      get :logout
    end
  end

  resources :top, only: [:index]

  resource :system_config,
    only: [:edit, :update] do
    member do
      post "edit", as: :edit
    end
  end

  resources :reasons,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :leave_types,
    only: [:index, :new, :edit],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :articles,
    only: [:index, :show, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :special_days,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :attendances,
    only: [:index, :destroy] do
    collection do
      match :save, via: :all
      post :specific_month
    end
  end

  root to: redirect("login/new")

  post "/toggle_sidebar" => "application#toggle_sidebar"

  # page not found
  get "*path", controller: "application", action: "render_404"
end

app/models/special_day.rb
# frozen_string_literal: true
class SpecialDay < ApplicationRecord
  # ?L???f?[?^
  scope :availability, -> {
    where(deleted: "0")
  }

  scope :holodays, -> {
    availability
      .where(day_type: CONSTANTS::SPECIAL_DAY_HOLIDAY_TYPE)
  }

  scope :business_days, -> {
    availability
      .where(day_type: CONSTANTS::SPECIAL_DAY_BUSINESS_DAY_TYPE)
  }

  validates :name,
            presence: true
  validates :day_type,
            presence: true
  validates :date_text,
            presence: true,
            date: { format: I18n.t(:date_format), allow_blank: true }

  def date
    Date.strptime(date_ymd, I18n.t(:default_date_format, separate: nil))
  rescue
    nil
  end

  def date_text
    return @date_text unless @date_text.blank?
    date.strftime(I18n.t(:date_format))
  rescue
    nil
  end

  def date_text=(value)
    date_value = Date.strptime(value, I18n.t(:date_format))
    self.date_ymd = date_value.strftime(I18n.t(:default_date_format, separate: nil))
  rescue
    self.date_ymd = nil
  ensure
    @date_text = value
  end

  def day_type
    return CONSTANTS::SPECIAL_DAY_HOLIDAY_TYPE if super.blank?
    super
  end

  def day_type_text
    CONSTANTS::SPECIAL_DAY_TYPES[day_type]
  end

  def soft_delete
    update(deleted: CONSTANTS::ENABLE_FLAG)
  end
end

app/controllers/special_days_controller.rb
# frozen_string_literal: true
class SpecialDaysController < ApplicationController
  before_action :required_admin_authority
  before_action :check_create_special_day_params, only: [:new]
  before_action :check_update_special_day_params, only: [:edit]

  def index
    @special_days = SpecialDay.availability
  end

  def new
    if request.get?
      @special_day = SpecialDay.new
    else
      @special_day.save
      flash[:notice] = t(".create_special_day")
      redirect_to special_days_path
    end
  end

  def edit
    if request.get?
      @special_day = SpecialDay.find(params[:id])
    else
      @special_day.save
      flash[:notice] = t(".update_special_day")
      redirect_to special_days_path
    end
  end

  def destroy
    SpecialDay.find(params[:id]).soft_delete
    flash[:notice] = t(".delete_special_day")
    redirect_to special_days_path
  end

  private

  def check_create_special_day_params
    return if params[:special_day].blank?
    @special_day = SpecialDay.new(special_day_params)
    return if @special_day.valid?
    render action: :new
  end

  def check_update_special_day_params
    return if params[:special_day].blank?
    @special_day = SpecialDay.find(params[:id])
    @special_day.attributes = special_day_params
    return if @special_day.valid?
    render action: :edit
  end

  def special_day_params
    params.require(:special_day).permit(
      :name,
      :date_text,
      :day_type
    )
  end
end

app/helpers/special_days_helper.rb
# frozen_string_literal: true
module SpecialDaysHelper
end

app/views/special_days/_form.html.erb
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:name) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :name, required: true, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:date_ymd) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :date_text, required: true, class: "datepicker form-control flat" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:day_type) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10 radio">
    <% CONSTANTS::SPECIAL_DAY_TYPES.each do |key, val| %>
      <label>
        <%= f.radio_button :day_type,
          key,
          class: "form-control icheck" %>
        <label>
          <%= val %>
        </label>
      </label>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $(".datepicker").datepicker({
      language: "ja",
      format:   "<%= t("datepicker.format") %>"
    }).on("changeDate", function(e){
      $(this).datepicker("hide");
    });

    $("input.icheck").iCheck({
      checkboxClass: "icheckbox_flat-blue",
      radioClass:    "iradio_flat-blue"
    });
  });
</script>

app/views/special_days/edit.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @special_day, url: { action: :edit }, html: { class: "form-horizontal" }, method: :post do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_special_day"),
                  data:  { disable_with: t(:processing) },
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), special_days_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/special_days/index.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"><%= t(".list") %></h3>
            </div>
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                  <table id="special_day_table" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>
                          <%= SpecialDay.human_attribute_name(:date_ymd) %>
                        </th>
                        <th>
                          <%= SpecialDay.human_attribute_name(:name) %>
                        </th>
                        <th>
                          <%= SpecialDay.human_attribute_name(:day_type) %>
                        </th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @special_days.each do |special_day| %>
                        <tr>
                          <td>
                            <%= special_day.date_text %>
                          </td>
                          <td>
                            <%= special_day.name %>
                          <td>
                            <%= special_day.day_type_text %>
                          </td>
                          <td>
                            <%= link_to t(".edit_special_day"), edit_special_day_path(special_day),
                              class: "btn btn-success" %>
                          </td>
                          <td>
                            <%= link_to t(".delete"), special_day_path(special_day),
                              method: :delete,
                              class:   "btn btn-danger" %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%== datatable_script("special_day_table",
                                        0,
                                        { order: "desc",
                                          column_defs: [-1, -2] }) %>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <%= link_to t(".new_special_day"), new_special_day_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
              <%= link_to t(".back"), top_index_path,
                method: :get,
                class:  "btn btn-primary btn-lg pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/special_days/new.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @special_day, url: { action: :new }, html: { class: "form-horizontal" } do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_special_day"),
                  data:  { disable_with: t(:processing) },
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), special_days_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>