config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :custom_restful do
    collection do
      post "new", as: :new
    end
    member do
      post "edit", as: :edit
    end
  end

  resources :login, only: [:new] do
    collection do
      post "new"
      get :logout
    end
  end

  resources :top, only: [:index]

  resource :system_config,
    only: [:edit, :update] do
    member do
      post "edit", as: :edit
    end
  end

  resources :reasons,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :leave_types,
    only: [:index, :new, :edit],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :articles,
    only: [:index, :show, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :special_days,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :attendances,
    only: [:index, :destroy] do
    collection do
      match :save, via: :all
      post :specific_month
    end
  end

  root to: redirect("login/new")

  post "/toggle_sidebar" => "application#toggle_sidebar"

  # page not found
  get "*path", controller: "application", action: "render_404"
end

app/controllers/leave_types_controller.rb
# frozen_string_literal: true
class LeaveTypesController < ApplicationController
  before_action :required_admin_authority
  before_action :prep_leave_types,               only: [:index, :change_orders]
  before_action :check_create_leave_type_params, only: [:new]
  before_action :check_update_leave_type_params, only: [:edit]

  def new
    if request.get?
      @leave_type = LeaveType.new
    else
      @leave_type.save
      flash[:notice] = t(".create_leave_type")
      redirect_to leave_types_path
    end
  end

  def edit
    if request.get?
      @leave_type = LeaveType.find(params[:id])
    else
      @leave_type.save
      flash[:notice] = t(".update_leave_type")
      redirect_to leave_types_path
    end
  end

  def destroy
    LeaveType.find(params[:id]).soft_delete
    flash[:notice] = t(".delete_leave_type")
    redirect_to leave_types_path
  end

  def update_orders
    leave_type = LeaveType.availability.find(params[:id])
    leave_type.change_order(params[:position])
    render json: { result: true }
  end

  private

  def prep_leave_types
    @leave_types = LeaveType.order_display
  end

  def check_create_leave_type_params
    return if params[:leave_type].blank?
    @leave_type = LeaveType.new(leave_type_params)
    return if @leave_type.valid?
    render action: :new
  end

  def check_update_leave_type_params
    return if params[:leave_type].blank?
    @leave_type = LeaveType.find(params[:id])
    @leave_type.attributes = leave_type_params
    return if @leave_type.valid?
    render action: :edit
  end

  def leave_type_params
    params.require(:leave_type).permit(:content,
                                       :status,
                                       :aggregate_display)
  end
end

app/helpers/leave_types_helper.rb
# frozen_string_literal: true
module LeaveTypesHelper
end

app/views/leave_types/_form.html.erb
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:content) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :content, required: true, class: "datepicker form-control flat" %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:status) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10 radio">
    <% CONSTANTS::LEAVE_TYPE_STATUSES.each do |key, val| %>
      <label>
        <%= f.radio_button :status,
          key,
          class: "form-control icheck" %>
        <label>
          <%= val %>
        </label>
      </label>
    <% end %>
  </div>
</div>
<div class="form-group">
  <%= f.label :aggregate_display, class: "col-sm-2 control-label" %>
  <div class="col-sm-10 radio">
    <%= f.check_box :aggregate_display, class: "form-control icheck" %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $("input.icheck").iCheck({
      checkboxClass: "icheckbox_flat-blue",
      radioClass:    "iradio_flat-blue"
    });
  });
</script>

app/views/leave_types/change_orders.html.erb
<%= javascript_include_tag "leave_types" %>
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"><%= t(".list") %></h3>
            </div>
            <div class="box-body">
              <ul class="todo-list sortable">
                <% @leave_types.each do |leave_type| %>
                  <li data-update_url="<%= update_orders_leave_type_path(leave_type) %>">
                    <span class="handle ui-sortable-handle">
                      <i class="fa fa-ellipsis-v"></i>
                      <i class="fa fa-ellipsis-v"></i>
                    </span>
                    <span class="text"><%= leave_type.content %></span>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="box-footer">
              <%= link_to t(".back"), leave_types_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
            </div>
            <div class="overlay hide">
              <i class="fa fa-refresh fa-spin"></i>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/leave_types/edit.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @leave_type, url: { action: :edit }, html: { class: "form-horizontal" }, method: :post do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_leave_type"),
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), leave_types_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/leave_types/index.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"><%= t(".list") %></h3>
              <div class="box-tools pull-right">
                <%= link_to change_orders_leave_types_path, class: "btn btn-info btn-sm" do %>
                  <span class="glyphicon glyphicon-sort"></span>
                <% end %>
              </div>
            </div>
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                  <table id="leave_type_table" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>
                          <%= LeaveType.human_attribute_name(:display_order) %>
                        </th>
                        <th>
                          <%= LeaveType.human_attribute_name(:content) %>
                        </th>
                        <th>
                          <%= LeaveType.human_attribute_name(:status) %>
                        </th>
                        <th>
                          <%= LeaveType.human_attribute_name(:aggregate_display) %>
                        </th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @leave_types.each do |leave_type| %>
                        <tr class="<%= 'bg-gray' if leave_type.disable? %>">
                          <td>
                            <%= leave_type.display_order %>
                          </td>
                          <td>
                            <%= leave_type.content %>
                          </td>
                          <td>
                            <%= leave_type.status_name %>
                          </td>
                          <td>
                            <% if leave_type.aggregate_display_enable? %>
                              <span class="glyphicon glyphicon-ok"></span>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to t(".edit_leave_type"), edit_leave_type_path(leave_type),
                              class: "btn btn-success" %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%== datatable_script("leave_type_table",
                                        0,
                                        { column_defs: [-1, -2] }) %>
                </div>
              </div>
            </div>
            <div class="box-footer">
              <%= link_to t(".new_leave_type"), new_leave_type_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
              <%= link_to t(".back"), top_index_path,
                method: :get,
                class:  "btn btn-primary btn-lg pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/leave_types/new.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @leave_type, url: { action: :new }, html: { class: "form-horizontal" } do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_leave_type"),
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), leave_types_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>