config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :custom_restful do
    collection do
      post "new", as: :new
    end
    member do
      post "edit", as: :edit
    end
  end

  resources :login, only: [:new] do
    collection do
      post "new"
      get :logout
    end
  end

  resources :top, only: [:index]

  resource :system_config,
    only: [:edit, :update] do
    member do
      post "edit", as: :edit
    end
  end

  resources :reasons,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :leave_types,
    only: [:index, :new, :edit],
    concerns: :custom_restful do
    collection do
      get :change_orders
    end
    member do
      post :update_orders
    end
  end

  resources :articles,
    only: [:index, :show, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :special_days,
    only: [:index, :new, :edit, :destroy],
    concerns: :custom_restful

  resources :attendances,
    only: [:index, :destroy] do
    collection do
      match :save, via: :all
      post :specific_month
    end
  end

  root to: redirect("login/new")

  post "/toggle_sidebar" => "application#toggle_sidebar"

  # page not found
  get "*path", controller: "application", action: "render_404"
end

app/models/reason.rb
# frozen_string_literal: true
class Reason < ApplicationRecord
  validates :content,
            presence: true

  before_save :set_display_order,
              if: :new_record?
  after_save :prepare_display_orders,
             if: :deleted?

  scope :availability, -> {
    where(deleted: CONSTANTS::DISABLE_FLAG)
  }

  scope :order_display, -> {
    availability
      .order(:display_order)
  }

  scope :position, ->(position) {
    order_display[position.to_i]
  }

  def change_order(position)
    pr = Reason.position(position)
    self.display_order, pr.display_order = pr.display_order, display_order
    save
    pr.save
  end

  def soft_delete
    update(deleted: CONSTANTS::ENABLE_FLAG)
  end

  def deleted?
    deleted == CONSTANTS::ENABLE_FLAG
  end

  private

  def set_display_order
    self.display_order = Reason.availability.maximum(:display_order).try(:next) || 1
  end

  def prepare_display_orders
    reasons = Reason.availability.where("display_order > ?", display_order)
    reasons.each do |reason|
      reason.decrement(:display_order)
      reason.save
    end
  end
end

app/controllers/reasons_controller.rb
# frozen_string_literal: true
class ReasonsController < ApplicationController
  before_action :required_admin_authority
  before_action :prep_reasons,               only: [:index, :change_orders]
  before_action :check_create_reason_params, only: [:new]
  before_action :check_update_reason_params, only: [:edit]

  def new
    if request.get?
      @reason = Reason.new
    else
      @reason.save
      flash[:notice] = t(".create_reason")
      redirect_to reasons_path
    end
  end

  def edit
    if request.get?
      @reason = Reason.find(params[:id])
    else
      @reason.save
      flash[:notice] = t(".update_reason")
      redirect_to reasons_path
    end
  end

  def destroy
    Reason.find(params[:id]).soft_delete
    flash[:notice] = t(".delete_reason")
    redirect_to reasons_path
  end

  def update_orders
    reason = Reason.availability.find(params[:id])
    reason.change_order(params[:position])
    render json: { result: true }
  end

  private

  def prep_reasons
    @reasons = Reason.order_display
  end

  def check_create_reason_params
    return if params[:reason].blank?
    @reason = Reason.new(reason_params)
    return if @reason.valid?
    render action: :new
  end

  def check_update_reason_params
    return if params[:reason].blank?
    @reason = Reason.find(params[:id])
    @reason.attributes = reason_params
    return if @reason.valid?
    render action: :edit
  end

  def reason_params
    params.require(:reason).permit(:content)
  end
end

app/helpers/reasons_helper.rb
# frozen_string_literal: true
module ReasonsHelper
end

app/views/reasons/_form.html.erb
<div class="form-group">
  <label class="col-sm-2 control-label">
    <%= f.object.class.human_attribute_name(:content) %>
    <%= required_marc %>
  </label>
  <div class="col-sm-10">
    <%= f.text_field :content, required: true, class: "datepicker form-control flat" %>
  </div>
</div>

app/views/reasons/change_orders.html.erb
<%= javascript_include_tag "reasons" %>
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"><%= t(".list") %></h3>
            </div>
            <div class="box-body">
              <ul class="todo-list sortable">
                <% @reasons.each do |reason| %>
                  <li data-update_url="<%= update_orders_reason_path(reason) %>">
                    <span class="handle ui-sortable-handle">
                      <i class="fa fa-ellipsis-v"></i>
                      <i class="fa fa-ellipsis-v"></i>
                    </span>
                    <span class="text"><%= reason.content %></span>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="box-footer">
              <%= link_to t(".back"), reasons_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
            </div>
            <div class="overlay hide">
              <i class="fa fa-refresh fa-spin"></i>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/reasons/edit.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @reason, url: { action: :edit }, html: { class: "form-horizontal" }, method: :post do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_reason"),
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), reasons_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/reasons/index.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <%= render "shares/flash_messages" %>

      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"><%= t(".list") %></h3>
              <div class="box-tools pull-right">
                <%= link_to change_orders_reasons_path, class: "btn btn-info btn-sm" do %>
                  <span class="glyphicon glyphicon-sort"></span>
                <% end %>
              </div>
            </div>
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                  <table id="reason_table" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>
                          <%= Reason.human_attribute_name(:display_order) %>
                        </th>
                        <th>
                          <%= Reason.human_attribute_name(:content) %>
                        </th>
                        <th></th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @reasons.each do |reason| %>
                        <tr>
                          <td>
                            <%= reason.display_order %>
                          </td>
                          <td>
                            <%= reason.content %>
                          <td>
                            <%= link_to t(".edit_reason"), edit_reason_path(reason),
                              class: "btn btn-success" %>
                          </td>
                          <td>
                            <%= link_to t(".delete"), reason_path(reason),
                              method: :delete,
                              class:   "btn btn-danger" %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <%== datatable_script("reason_table",
                                        0,
                                        { column_defs: [-1, -2] }) %>
                </div>
              </div>            </div>
            <div class="box-footer">
              <%= link_to t(".new_reason"), new_reasons_path,
                method: :get,
                class:  "btn btn-primary btn-lg" %>
              <%= link_to t(".back"), top_index_path,
                method: :get,
                class:  "btn btn-primary btn-lg pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>

app/views/reasons/new.html.erb
<div class="wrapper">
  <%= render "layouts/main_header" %>
  <%= render "layouts/main_sidebar" %>

  <div class="content-wrapper">
    <section class="content-header">
      <h1><%= t(".title") %></h1>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <%= form_for @reason, url: { action: :new }, html: { class: "form-horizontal" } do |f| %>
              <div class="box-body">
                <%= render partial: "form", locals: { f: f } %>
              </div>
              <div class="box-footer">
                <%= f.submit t(".save_reason"),
                  class: "btn btn-primary btn-lg" %>
                <%= link_to t(".back"), reasons_path,
                  class: "btn btn-primary btn-lg pull-right" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>
  </div>

  <%= render "layouts/main_footer" %>
</div>